# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  enconding: unicode
  username: castengo
  password:


# development:
#   <<: *default
#   database: db/development.sqlite3
#
# test:
#   <<: *default
#   database: db/test.sqlite3

development:
  <<: *default
  database: db/myapp_dev

test:
  <<: *default
  database: db/myapp_test

production:
  <<: *default
