# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0f26e23b1d3112a29e987ed7bb0b4cc4e599d11448faac98b36a1694030e31a4c3016e9acefbb43f78dc577e4868565bb4434384f380f4e0bf63931bf36f7d

test:
  secret_key_base: d56ba7eb0da6e8bf23a3150d6c5ab38aa00644a3f6b782475f34d76cba4133be41cbca7e10a4d1cfb6b53c3e6e48cb52d4ff90a2cbd7c396980415c9e26b05be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
